<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
    <None Remove="Assets\fault.png" />
    <None Remove="Assets\good.png" />
    <None Remove="Assets\info.png" />
    <None Remove="Assets\logo.png" />
    <None Remove="Assets\nastr.png" />
    <None Remove="Assets\Next.png" />
    <None Remove="Assets\return.png" />
    <None Remove="Assets\Start.png" />
    <None Remove="Assets\Stop.png" />
    <None Remove="Assets\toggle_close.png" />
    <None Remove="Assets\toggle_open.png" />
    <None Remove="Assets\warning.png" />
    <None Remove="lib\CodeReaderSdkConfig.ini" />
    <None Remove="lib\hlog.dll" />
    <None Remove="lib\hpr.dll" />
    <None Remove="lib\log4cxx.properties" />
    <None Remove="lib\msvcr90.dll" />
    <None Remove="lib\MvCodeReaderCtrl.dll" />
    <None Remove="lib\MvCodeReaderCtrlWrapper.dll" />
    <None Remove="lib\MvCodeReaderSDK.Net.dll" />
    <None Remove="lib\MvZip.dll" />
    <None Remove="lib\VirXMLParse.dll" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\fault.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\good.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\warning.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="lib\CodeReaderSdkConfig.ini">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="lib\hlog.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="lib\hpr.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="lib\log4cxx.properties">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="lib\msvcr90.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="lib\MvCodeReaderCtrl.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="lib\MvCodeReaderCtrlWrapper.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="lib\MvCodeReaderSDK.Net.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="lib\MvZip.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="lib\VirXMLParse.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EasyModbusTCP" Version="5.6.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.12" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="10.0.2" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
    <PackageReference Include="System.IO.Ports" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LabelDesigner\LabelDesigner.csproj" />
    <ProjectReference Include="..\Observable\Observable.csproj" />
  </ItemGroup>
    <ItemGroup>
    <Reference Include="MvCodeReaderSDK.Net">
      <HintPath>lib\MvCodeReaderSDK.Net.dll</HintPath>
    </Reference>
    <Reference Include="MvCodeReaderCtrl">
      <HintPath>lib\MvCodeReaderCtrl.dll</HintPath>
    </Reference>
    <Reference Include="MvCodeReaderCtrlWrapper">
      <HintPath>lib\MvCodeReaderCtrlWrapper.dll</HintPath>
    </Reference>
  </ItemGroup>
    <ItemGroup>
      <Resource Include="Assets\info.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\logo.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\nastr.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Next.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\return.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Start.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\Stop.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\toggle_close.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <Resource Include="Assets\toggle_open.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
    </ItemGroup>
  <!-- Копирование всех файлов из lib в bin -->
  <ItemGroup>
    <None Update="lib\**\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="label.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
